version: "3.8"

services:
  district-name-python-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../district-data:/app/district-data
      - ../../unzip-src:/app/unzip-src
    container_name: district-name-python-pipeline
    command: python main.py
