version: '3.8'

services:
  apigateway:
    image: nginx:latest
    container_name: apigateway
    ports:
      - "80:80"
    volumes:
      - ./APIGateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - userservice
    networks:
      - be-network

  userservice:
    build:
      context: ./UserService/Server
      dockerfile: Dockerfile
    container_name: userservice
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_PORT=3306
      - MYSQL_DB=userservice_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysqldb
      - redis
    networks:
      - be-network

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: userservice_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - be-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - be-network

networks:
  be-network:
    driver: bridge

volumes:
  mysql_data:
    name: custom_mysql_data
